tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/cask-fonts'

brew 'ack'
brew 'archey'
brew 'asdf'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'ctags'
brew 'curl'
brew 'dos2unix'
brew 'gh'
brew 'git'
brew 'mas'
brew 'node'
brew 'nvim'
brew 'pgcli'
brew 'pidof'
brew 'postgresql'
brew 'prettier'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'

cask 'adobe-acrobat-reader'
cask 'alfred'
cask 'caffeine'
cask 'firefox'
cask 'font-jetbrains-mono'
cask 'fork'
cask 'google-chrome'
cask 'iterm2'

mas 'LastPass', id: 926036361
mas 'Magnet', id: 441258766
mas 'Tweetbot', id: 1384080005
